name: "ü™µ Terraform Apply: prod-control-tower ‚úàÔ∏è"

env:
  TF_VAR_github_environment: prod-control-tower    

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - prod-control-tower/terraform/**
  workflow_dispatch:
    inputs:
      TerraformLogLevel:
        description: 'Terraform Log Level'
        required: false
        default: 'INFO'
        type: choice
        options:
          - TRACE
          - DEBUG
          - INFO
          - WARN
          - ERROR

jobs:

  inform_about_apply:
    name: Inform About Apply
    environment: prod-control-tower
    runs-on: ubuntu-20.04

    steps:
      - name: Inform on PR that Apply is Running
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ***Running terraform apply for `prod-control-tower` ‚úàÔ∏è***
            Results will display here momentarily...

  terraform-apply:
    name: "Tü™µ Terraform Apply: prod-control-tower ‚úàÔ∏è"
    environment: prod-control-tower
    runs-on: ubuntu-latest
    env:
      TF_LOG: ${{ inputs.logLevel }}
      TF_VAR_github_environment: prod-control-tower
    defaults:
      run:
        working-directory: prod-control-tower/terraform/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Source Environment Variables
        id: dotenv
        uses: falti/dotenv-action@v1.0.2
        with:
          path: '.github/workflows/.env.prod-control-tower'

      - name: Configure AWS Credentials for creating resources
        #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ steps.dotenv.outputs.aws_account_id }}:role/${{ steps.dotenv.outputs.aws_workflow_role }}
          role-session-name: ${{ github.actor }}_${{ github.job }}
          aws-region: ${{ steps.dotenv.outputs.aws_region }}

      - name: Setup Python # We use this for a Terraform Data source that calls a Python script
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install boto3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ steps.dotenv.outputs.TERRAFORM_VERSION }}

      - name: Get GitHub Apps Token # This enables access to Terraform modules in internal/private repos
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.ORG_REPO_READ_PRIVATE_KEY }}
          APP_ID: ${{ secrets.ORG_REPO_READ_APP_ID }}
        # Doc: https://github.com/machine-learning-apps/actions-app-token

      - name: Enable Terraform Git actions to use Github Apps Token
        uses: de-vri-es/setup-git-credentials@v2.0.10
        with:
          credentials: https://git:${{ steps.get_token.outputs.app_token }}@github.com
        # Doc: https://maelvls.dev/gh-actions-with-tf-private-repo/

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=terraform.tfplan -var-file="variables-prod-control-tower.tfvars"
        continue-on-error: true

      # - name: Download artifacts
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     workflow: terraform-plan.yml
      #     workflow_conclusion: success
      #     github_token: ${{ secrets.ARTIFACT_TOKEN }}

      # # - name: List Files
      # #   run: ls -lahR

      # - name: Untar Files
      #   run: tar -xvf plan/plan_artifacts.tar .
      #   #run: mv plan/* .; mv plan/.[!.]* . # Copy files (including dotfiles from the plan)

      # - name: List Files
      #   run: ls -lahR

      - name: Terraform Apply
        id: apply
        #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        # run: terraform show terraform.tfplan # During Testing
        run: terraform apply -input=false -no-color terraform.tfplan
        continue-on-error: true

      - name: Post Apply Success to GitHub PR
        if: steps.apply.outcome == 'success'
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            Applying Terraform in prod-control-tower ‚úàÔ∏è:

            ```
            ${{ steps.apply.outputs.stdout }}
            ```

      - name: Post Apply Failure to GitHub PR
        if: steps.apply.outcome == 'failure'
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            Apply failed for Terraform in prod-control-tower ‚úàÔ∏è:

            ```
            ${{ steps.apply.outputs.stderr }}
            ```

      # - name: Notify Mirosoft Teams On Success
      #   if: steps.apply.outcome == 'success'
      #   uses: jdcargile/ms-teams-notification@v1.3
      #   with:
      #     github-token: ${{ github.token }} # this will use the runner's token.
      #     ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
      #     notification-summary: Terraform Apply Succeeded
      #     notification-color: 34eb5c #Green
      #     #timezone: America/Denver

      # - name: Notify Mirosoft Teams On Failure
      #   if: steps.apply.outcome == 'failure'
      #   uses: jdcargile/ms-teams-notification@v1.3
      #   with:
      #     github-token: ${{ github.token }} # this will use the runner's token.
      #     ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
      #     notification-summary: Terraform Apply Failed
      #     notification-color: eb4034 #Red
      #     #timezone: America/Denver

      - name: Terraform Apply Status
        if: steps.apply.outcome == 'failure'
        run: exit 1      
